<a href="https://colab.research.google.com/github/26wh5a0505-ux/WEEKK-2/blob/main/WEEK%202/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [88]:
# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])

# 1.2 Create a 3x4 NumPy array with random integers from 1 to 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))

# 1.3 Convert the NumPy array to a DataFrame
df1_3 = pd.DataFrame(
    np_array1_2,
    columns=['A', 'B', 'C', 'D']
)

# Optional: display the results
print("\ns1_1:")
print(s1_1)

print("\nnp_array1_2:")
print(np_array1_2)

print("\ndf1_3:")
print(df1_3)



s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

np_array1_2:
[[75 65 10 92]
 [37 22 51 69]
 [66 47 49 26]]

df1_3:
    A   B   C   D
0  75  65  10  92
1  37  22  51  69
2  66  47  49  26


In [94]:

dates = pd.date_range(start='2023-01-01', end='2023-04-09', periods=100)
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100).astype(float),
    'Quantity': np.random.randint(1, 11, size=100).astype(float)
})
sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan

print(df_sales)


                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000  North   Monitor  447.0       8.0
1  2023-01-01 23:45:27.272727272   West    Laptop  391.0       1.0
2  2023-01-02 23:30:54.545454545  North    Laptop  511.0       6.0
3  2023-01-03 23:16:21.818181818   West   Monitor  913.0       5.0
4  2023-01-04 23:01:49.090909090  South   Monitor  724.0       5.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910  South   Monitor  319.0       6.0
96 2023-04-06 00:43:38.181818182   West    Laptop  463.0       2.0
97 2023-04-07 00:29:05.454545455  South    Laptop    NaN       NaN
98 2023-04-08 00:14:32.727272728  North  Keyboard  941.0       4.0
99 2023-04-09 00:00:00.000000000  South     Mouse  262.0       5.0

[100 rows x 5 columns]


In [90]:

df3_1 = df_sales[['Region', 'Sales']]

print("\n3.1 Region and Sales:")
print(df3_1)
df3_2 = df_sales[df_sales['Product'] == 'Laptop']

print("\n3.2 Laptop rows:")
print(df3_2)
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]

print("\n3.3 East region with Sales > 500:")
print(df3_3)
monitor_rows = df_sales[df_sales['Product'] == 'Monitor']
first_monitor_index = monitor_rows.index[0]
val3_4 = df_sales.loc[first_monitor_index, 'Sales']
val3_4 = df_sales.iloc[
    df_sales.index.get_loc(first_monitor_index),
    df_sales.columns.get_loc('Sales')
]

print("\n3.4 First Monitor Sales value:", val3_4)



3.1 Region and Sales:
   Region  Sales
0   North  155.0
1   North  554.0
2   South  918.0
3   South  674.0
4   South  253.0
..    ...    ...
95  North  710.0
96  North  769.0
97  South  497.0
98   East    NaN
99  North  786.0

[100 rows x 2 columns]

3.2 Laptop rows:
                            Date Region Product  Sales  Quantity
6  2023-01-06 22:32:43.636363636  North  Laptop  729.0      10.0
9  2023-01-09 21:49:05.454545454  South  Laptop  114.0       8.0
10 2023-01-10 21:34:32.727272727   East  Laptop  767.0       6.0
11 2023-01-11 21:20:00.000000000  North  Laptop  860.0       7.0
12 2023-01-12 21:05:27.272727272  North  Laptop  322.0       2.0
17 2023-01-17 19:52:43.636363636  North  Laptop  550.0       6.0
18 2023-01-18 19:38:10.909090909  North  Laptop  679.0       9.0
21 2023-01-21 18:54:32.727272727   East  Laptop  176.0       NaN
30 2023-01-30 16:43:38.181818182  South  Laptop  707.0       7.0
32 2023-02-01 16:14:32.727272727  South  Laptop  365.0      10.0
34 2023-02-03 15

In [91]:

missing_counts4_1 = df_sales.isna().sum()

print("\n4.1 Missing values:")
print(missing_counts4_1)
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()

df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

print("\n4.2 DataFrame after filling Sales:")
print(df4_2_filled)
df4_3_dropped = df_sales.dropna()

print("\n4.3 DataFrame after dropping missing rows:")
print(df4_3_dropped)



4.1 Missing values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

4.2 DataFrame after filling Sales:
                            Date Region   Product       Sales  Quantity
0  2023-01-01 00:00:00.000000000  North     Mouse  155.000000       7.0
1  2023-01-01 23:45:27.272727272  North  Keyboard  554.000000       2.0
2  2023-01-02 23:30:54.545454545  South  Keyboard  918.000000       9.0
3  2023-01-03 23:16:21.818181818  South     Mouse  674.000000       2.0
4  2023-01-04 23:01:49.090909090  South     Mouse  253.000000       9.0
..                           ...    ...       ...         ...       ...
95 2023-04-05 00:58:10.909090910  North  Keyboard  710.000000      10.0
96 2023-04-06 00:43:38.181818182  North     Mouse  769.000000       5.0
97 2023-04-07 00:29:05.454545455  South  Keyboard  497.000000       5.0
98 2023-04-08 00:14:32.727272728   East   Monitor  553.178947       2.0
99 2023-04-09 00:00:00.000000000  North   Monitor  786.000000       

In [92]:
# 5.1 Create Total_Revenue column
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

print("\n5.1 Total_Revenue:")
print(df_sales[['Sales', 'Quantity', 'Total_Revenue']])
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

print("\n5.2 Sorted DataFrame:")
print(df5_2_sorted)
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

print("\n5.3 Grouped by Region:")
print(df5_3_grouped_region)
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\n5.4 Average Sales by Product:")
print(df5_4_grouped_product)



5.1 Total_Revenue:
    Sales  Quantity  Total_Revenue
0   155.0       7.0         1085.0
1   554.0       2.0         1108.0
2   918.0       9.0         8262.0
3   674.0       2.0         1348.0
4   253.0       9.0         2277.0
..    ...       ...            ...
95  710.0      10.0         7100.0
96  769.0       5.0         3845.0
97  497.0       5.0         2485.0
98    NaN       2.0            NaN
99  786.0       3.0         2358.0

[100 rows x 3 columns]

5.2 Sorted DataFrame:
                            Date Region   Product  Sales  Quantity  \
0  2023-01-01 00:00:00.000000000  North     Mouse  155.0       7.0   
1  2023-01-01 23:45:27.272727272  North  Keyboard  554.0       2.0   
2  2023-01-02 23:30:54.545454545  South  Keyboard  918.0       9.0   
3  2023-01-03 23:16:21.818181818  South     Mouse  674.0       2.0   
4  2023-01-04 23:01:49.090909090  South     Mouse  253.0       9.0   
..                           ...    ...       ...    ...       ...   
95 2023-04-05 00:58:10.